<?php if(ICL_LANGUAGE_CODE=='en'){ 
	echo 'Back';
} ?>
<?php if(ICL_LANGUAGE_CODE=='nl'){ 
	echo 'Terug';
} ?>
<?php if(ICL_LANGUAGE_CODE=='fr'){ 
	echo 'Retour';
} ?>
<?php if(ICL_LANGUAGE_CODE=='cs'){ 
	echo 'ZPĚT';
} ?>